### ISSUE TITLE
Question regarding join & fetch

### ISSUE THREAD

**Issue by borillo** [my2iu/Jinq#10]
Hi Ming,

First of all, Jinq seems a very promissing library in comparision to existing options like QueryDSL.
Thanks for that ;)

As i can see in the documentation, when i want to execute a JOIN and FETCH all the related records, i have to do:

    List<Country> countries = 
       streams.streamAll(em, Country.class)
          .where(c -> c.getContinent.equals("Europe"))
          .joinFetchList(c -> c.getCities())
          .toList();
    	  
    for (Country c: countries) {
       System.out.println("Cities in country: " + c.getName());
    
       for (City city: c.getCities()) {
          System.out.println("   " + city.getName());
       }
    }

The problem is that using maven version 1.8.4 of Jinq, the API differs and the main entity is not filled with its related childs, executing one query per each record. See my example:

    List<Pair<Master, Detail>> records = reportsStream
            .where(m -> m.getId() <= QUERY_LIMIT)
            .joinList(m -> m.getDetails())
            .toList();
    
    for (Pair<Master, Detail> record : records)
        System.out.println(record.getOne().getDetails().size());

See also that current version doesn't offer the joinFetchList method and the return type can't be List<Master> as i would expect ...

Any clues on this?

Best regards,
   Ricardo

**Comment by my2iu** [comment]
Version 1.8.4 should support joinFetchList(). JOIN FETCH operations are for JPQL queries only, so the API is inside the JPAJinqStream class instead of the normal JinqStream class. If you need access to JOIN FETCH queries, you will need to use JPAJinqStream instead of JinqStream.

For your second query, the issue is more related to how JPA works. In that case, Hibernate (or whatever JPA provider you are using) is not able to infer that the details from the query should be part of the records, so it doesn't link them together. As a result, it executes a new query each time you access the list. Of course, since you already have the details in the pair, you can simply access them that way. I'm not sure if there is a way to fix this issue with Hibernate.

**Comment by borillo** [comment]
Cool. Now it works with JPAJinqStream. Thx!!
