### ISSUE TITLE
SQL "LIKE" statement

### ISSUE THREAD

**Issue by borillo** [my2iu/Jinq#11]
Hi again Ming,

I'm trying to query a table with a "LIKE" expressión removing diacritical marks. Something like:

    private String clean(String name) {
        String result = Normalizer.normalize(name, Normalizer.Form.NFD);
        return result.replaceAll("[\\p{InCombiningDiacriticalMarks}]", "");
    }

    ...

    JinqJPAStreamProvider streams = new JinqJPAStreamProvider(entityManager.getMetamodel());
    JPAJinqStream<Master> reportsStream = streams.streamAll(entityManager, Master.class);

    List<Master> records = reportsStream
            .where(master -> clean(master.getName()).indexOf("values") > 0)
            .toList();

But i get an error:

    java.lang.IllegalArgumentException: Could not extract code from lambda. This error sometimes occurs because your lambda references objects that aren't Serializable.
        at org.jinq.jpa.transform.LambdaInfo.analyze(LambdaInfo.java:33)    

Do you know it there's any way to perform this operation?

BTW i had to use "indexOf" becuase "contains" was not working :(

Thanks a lot for your help and best regards,
  Ricardo

**Comment by my2iu** [comment]
I guess there's three things going on here:

1. The error happens because when you call the "clean()" method, a pointer to the "this" object is included in the lambda function. Due to issues with Java 8, if "this" is not Serializable, it prevents Jinq from analyzing the lambda function and converting it to a database query.

2. The "clean()" method and "indexOf()" method can't be mapped to a database operation, so the query cannot be converted by Jinq into a database query. One solution is to do this filtering on the application server (read all the names, normalize them, then filter them, and then read in the full records of the ones that match). Another is to add an extra field in the database with a pre-normalized version of the name, then you don't need to run special code to normalize the names as you filter them. A third possibility is to use stored procedures on the database that lets you run your own code on the database server, but Jinq currently does not support stored procedures.

3. Jinq has support for "LIKE" operations via the JPQL.like() method.

**Comment by my2iu** [comment]
Jinq has proper support for LIKE, contains(), and indexOf() now, so I think this issue is no longer a problem and I am closing this issue.
