### ISSUE TITLE
[BUG]: The concatenation of strings was not as expected

### ISSUE THREAD

**Issue by zdu-strong** [my2iu/Jinq#115]
The concatenation of strings was not as expected.

Expected:   "a" + "b" + "c" = "abc"

Actual:       "a" + "b" + "c" = "cba"

![image](https://github.com/my2iu/Jinq/assets/48673442/16e3d8ac-c7b0-482d-9d8a-34d8a1184501)
![image](https://github.com/my2iu/Jinq/assets/48673442/0d3a3032-985e-4ac5-90ee-316feee3cc8e)

My Repository: [https://github.com/zdu-strong/Temp_Test_Of_Jinq](https://github.com/zdu-strong/Temp_Test_Of_Jinq)
Require Enviroment: java v21
Run Command: ./mvn clean test

**Comment by my2iu** [comment]
I'll take a look. On some of the compilers of newer JDKs, Java generates code that uses a lot of runtime code generation for string concatenation, and this code generation isn't documented too well, so it's been hard to get the code analysis for that stuff to work right.

**Comment by my2iu** [comment]
Concatenation of 2 things probably works fine, so if you need a workaround while I figure out what's going on, you could try something like:

```
select((s) -> {
   String temp = s.getName() + "a";
  return temp + "b";
}
```

**Comment by zdu-strong** [comment]
Thank you so much.

**Comment by my2iu** [comment]
It turns out, I simply wasn't handling string literals that were more than one character long. When I was trying to figure out the lambda stuff, I kept reversing and unreversing the passed in values to make things consistent, but as a result, I ended up reversing string literals that were longer than a single character.

Maven should now have a version 2.02 and 1.8.37 that should fix this issue.
