### ISSUE TITLE
Simplify getting started page

### ISSUE THREAD

**Issue by benmccann** [my2iu/Jinq#15]
The [getting started page](http://www.jinq.org/docs/gettingstartedjpa.html) says that you have to download and compile Jinq to get started. It would be preferable if it let the user know that Jinq is available via Maven Central since that's how most people will want to use the library

**Comment by my2iu** [comment]
It's a little tricky. Because Jinq is a coding library, people need some sample code that they can compile and play with in order to see how all the pieces fit together. I'll try to play with the wording a bit to see if I can make things more clear that you're just working with a small JPA project and not compiling all of Jinq.

**Comment by my2iu** [comment]
I've reworded the Getting Started page to make it more clear that you're only downloading and compiling some sample code. People might still get confused about what steps are needed to use Jinq in a real project, but I can't really figure out a better way of explaining things. Since Jinq is built on top of JPA, you need to have a JPA project available to test Jinq, and many people don't have that sitting around--hence the need for sample code. And some people don't use Maven--they just use whatever code and build files that their IDE generates--so I don't want to have only Maven instructions for building that sample code.
