### ISSUE TITLE
unable to count after sorted

### ISSUE THREAD

**Issue by ggitt** [my2iu/Jinq#49]
stream.sortedBy(i -> i.getWeight()).count() : Could not translate code to a query
stream.count() : works

**Comment by my2iu** [comment]
This is a known limitation:

**Comment by ggitt** [comment]
Thank you for your response. sortedBy().count() worked on 1.8.7 version, it is good for paging query which require a total number to be returned , after upgrading to 1.8.17, all our old code failed to run.

to work around, we have to change our code: 
    stream = stream.where(i -> i.getType().equals(type)).sortedBy(i -> i.getWeight());
    PageImpl<Product> productList = queryForPageBean(stream, currPage, pageSize);
TO:
    stream = stream.where(i -> i.getType().equals(type));
    JinqStream<Product> countableStream = stream;
    stream = stream.sortedBy(i -> i.getWeight());
    PageImpl<Product> productList = queryForPageBean(stream, countableStream, currPage, pageSize); 

Is it possible to provide a method to unset the sort condition?    

Anyway,thank you very much for your effort.

**Comment by my2iu** [comment]
I'll see if I can find some time to look at this over the weekend.

**Comment by my2iu** [comment]
It actually turns out a little bit trickier than I thought because it also ends up affecting GROUP BY and subqueries and calculating multiple aggregates at once. Doing it right actually involves a lot of testing to make sure everything still makes sense, so I'll have to put this change aside until I can find an appropriate chunk of time to fix it.

**Comment by ggitt** [comment]
Ok, thanks.

**Comment by my2iu** [comment]
I've added the ability to calculate single aggregates on sorted data in Jinq 1.8.18.
