### ISSUE TITLE
Auto register CustomTuples Contructors

### ISSUE THREAD

**Issue by WiLLStenico** [my2iu/Jinq#64]
First of all congrats for the project.

Just a suggestion and an opinion request.
I believe the custom tuples is used in general for getting custom data and all the constructor is important. In my project I´m thinking add this method on my JinqRepository to set all constructors automatically when I want use.

I believe that can help my team, for example, use the feature without "need to remember to register custom tuples constructors".

That´s just an sketch, what´s your opinion about?

`
public JPAJinqStream registerReturn(Class<?> U){
		
		 Constructor<?>[] constructors = U.getConstructors();
		for (Constructor<?> constructor : constructors) {
			streams.registerCustomTupleConstructor(constructor);			
		}
		
		return this;
}
`

Following this line, maybe put the register inside select... Is it possible?

**Comment by my2iu** [comment]
It's an interesting idea, but I don't think custom tuples are that common. Jinq would normally be used in standard CRUD applications where people want the actual entities because they want to be able to modify them and write them back to the database.

This approach wouldn't work for Jinq in particular because people might have classes with many different constructors, only some of which are safe to use with Jinq. If all the constructors are registered, then Jinq will start throwing errors unexpectedly.
